Repository MarcioLMM/tcc-faculdade, pull requests merged in 2019-08, with the labels that each got.

#43 Frontend#32 Angular estruturação
  3jobs-web/Estruturação.md
Labels: Analyze, Front end

#45 Frontend#42 Ajuste no design
  3jobs-web/three-jobs-client/src/app/app.component.html
  3jobs-web/three-jobs-client/src/app/app.component.ts
  3jobs-web/three-jobs-client/src/app/modules/home/components/about-section/about-section.component.html
  3jobs-web/three-jobs-client/src/app/modules/home/components/about-section/about-section.component.scss
  3jobs-web/three-jobs-client/src/app/modules/home/components/feedback-section/feedback-section.component.html
  3jobs-web/three-jobs-client/src/app/modules/home/components/feedback-section/feedback-section.component.scss
  3jobs-web/three-jobs-client/src/app/modules/home/components/home-section/home-section.component.html
  3jobs-web/three-jobs-client/src/app/modules/home/components/home-section/home-section.component.scss
  3jobs-web/three-jobs-client/src/app/modules/home/pages/home/home.component.html
  3jobs-web/three-jobs-client/src/app/modules/home/pages/home/home.component.scss
  3jobs-web/three-jobs-client/src/app/modules/home/pages/home/home.component.ts
  3jobs-web/three-jobs-client/src/app/modules/testes/pages/testes/testes.component.html
  3jobs-web/three-jobs-client/src/app/shared/header/header.component.html
  3jobs-web/three-jobs-client/src/app/shared/header/header.component.scss
  3jobs-web/three-jobs-client/src/app/shared/header/header.component.ts
  3jobs-web/three-jobs-client/src/assets/global-styles.scss
Labels: Front end, bug, ui/ux

#40 Frontend#14 Criação da pagina de perfil
  3jobs-web/three-jobs-client/package-lock.json
  3jobs-web/three-jobs-client/package.json
  3jobs-web/three-jobs-client/src/app/core/core.module.ts
  3jobs-web/three-jobs-client/src/app/core/mocks/profile-interceptor.ts
  3jobs-web/three-jobs-client/src/app/core/services/profile.service.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/components/abilities/abilities.component.html
  3jobs-web/three-jobs-client/src/app/modules/profile/components/abilities/abilities.component.spec.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/components/abilities/abilities.component.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/components/academic-formation/academic-formation.component.html
  3jobs-web/three-jobs-client/src/app/modules/profile/components/academic-formation/academic-formation.component.spec.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/components/academic-formation/academic-formation.component.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/components/card-template/card-template.component.html
  3jobs-web/three-jobs-client/src/app/modules/profile/components/card-template/card-template.component.scss
  3jobs-web/three-jobs-client/src/app/modules/profile/components/card-template/card-template.component.spec.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/components/card-template/card-template.component.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/components/components.scss
  3jobs-web/three-jobs-client/src/app/modules/profile/components/experience/experience.component.html
  3jobs-web/three-jobs-client/src/app/modules/profile/components/experience/experience.component.spec.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/components/experience/experience.component.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/components/personal-data/personal-data.component.html
  3jobs-web/three-jobs-client/src/app/modules/profile/components/personal-data/personal-data.component.spec.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/components/personal-data/personal-data.component.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/components/user-address/user-address.component.html
  3jobs-web/three-jobs-client/src/app/modules/profile/components/user-address/user-address.component.spec.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/components/user-address/user-address.component.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/pages/profile/profile.component.html
  3jobs-web/three-jobs-client/src/app/modules/profile/pages/profile/profile.component.scss
  3jobs-web/three-jobs-client/src/app/modules/profile/pages/profile/profile.component.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/profile-routing.module.ts
  3jobs-web/three-jobs-client/src/app/modules/profile/profile.module.ts
  3jobs-web/three-jobs-client/src/app/modules/testes/pages/testes/testes.component.ts
  3jobs-web/three-jobs-client/src/app/shared/form/maintain-form.ts
  3jobs-web/three-jobs-client/src/app/shared/models/address.spec.ts
  3jobs-web/three-jobs-client/src/app/shared/models/address.ts
  3jobs-web/three-jobs-client/src/app/shared/models/profile.spec.ts
  3jobs-web/three-jobs-client/src/app/shared/models/profile.ts
  3jobs-web/three-jobs-client/src/app/shared/pipes/age.pipe.spec.ts
  3jobs-web/three-jobs-client/src/app/shared/pipes/age.pipe.ts
  3jobs-web/three-jobs-client/src/app/shared/shared.module.ts
Labels: Front end

#47 Frontend#17 Criação da pagina de detalhes de uma vaga
  3jobs-web/three-jobs-client/src/app/app-routing.module.ts
  3jobs-web/three-jobs-client/src/app/modules/job-details/job-details-routing.module.ts
  3jobs-web/three-jobs-client/src/app/modules/job-details/job-details.module.ts
  3jobs-web/three-jobs-client/src/app/modules/job-details/pages/job-details/job-details.component.html
  3jobs-web/three-jobs-client/src/app/modules/job-details/pages/job-details/job-details.component.spec.ts
  3jobs-web/three-jobs-client/src/app/modules/job-details/pages/job-details/job-details.component.ts
Labels: Front end

#48 Frontend#16 Criação da pagina de busca
  3jobs-web/three-jobs-client/src/app/app-routing.module.ts
  3jobs-web/three-jobs-client/src/app/modules/search/components/card-candidate/card-candidate.component.html
  3jobs-web/three-jobs-client/src/app/modules/search/components/card-candidate/card-candidate.component.spec.ts
  3jobs-web/three-jobs-client/src/app/modules/search/components/card-candidate/card-candidate.component.ts
  3jobs-web/three-jobs-client/src/app/modules/search/components/card-job/card-job.component.html
  3jobs-web/three-jobs-client/src/app/modules/search/components/card-job/card-job.component.spec.ts
  3jobs-web/three-jobs-client/src/app/modules/search/components/card-job/card-job.component.ts
  3jobs-web/three-jobs-client/src/app/modules/search/pages/search/search.component.html
  3jobs-web/three-jobs-client/src/app/modules/search/pages/search/search.component.spec.ts
  3jobs-web/three-jobs-client/src/app/modules/search/pages/search/search.component.ts
  3jobs-web/three-jobs-client/src/app/modules/search/search-routing.module.ts
  3jobs-web/three-jobs-client/src/app/modules/search/search.module.ts
Labels: Front end

#63 Frontend#35 Criação do Login #35
  .gitignore
  3jobs-web/three-jobs-client/src/app/core/core.module.ts
  3jobs-web/three-jobs-client/src/app/core/services/auth.service.spec.ts
  3jobs-web/three-jobs-client/src/app/core/services/auth.service.ts
  3jobs-web/three-jobs-client/src/app/core/services/entity.service.ts
  3jobs-web/three-jobs-client/src/app/core/services/user.service.spec.ts
  3jobs-web/three-jobs-client/src/app/core/services/user.service.ts
  3jobs-web/three-jobs-client/src/app/modules/home/components/account-modal/account-modal.component.html
  3jobs-web/three-jobs-client/src/app/modules/home/components/account-modal/account-modal.component.scss
  3jobs-web/three-jobs-client/src/app/modules/home/components/account-modal/account-modal.component.ts
  3jobs-web/three-jobs-client/src/app/modules/home/components/home-section/home-section.component.html
  3jobs-web/three-jobs-client/src/app/modules/home/components/login-modal/login-modal.component.html
  3jobs-web/three-jobs-client/src/app/modules/home/components/login-modal/login-modal.component.spec.ts
  3jobs-web/three-jobs-client/src/app/modules/home/components/login-modal/login-modal.component.ts
  3jobs-web/three-jobs-client/src/app/modules/home/home.module.ts
  3jobs-web/three-jobs-client/src/app/modules/home/pages/home/home.component.html
  3jobs-web/three-jobs-client/src/app/shared/form/maintain-form.ts
  3jobs-web/three-jobs-client/src/environments/environment.ts
Labels: Front end
